dist: bionic
sudo: required
language: python
python:
  - '3.6'
services:
  - docker
env:
  TRAVIS=true

before_install:
  - docker pull scartography/opensartoolkit:latest
  - docker run scartography/opensartoolkit:latest /bin/sh -c "cd OpenSarToolkit; pytest -v --cov=ost tests/;"

script:
  - pytest -v --cov=ost tests/
