language: python
python:
  - '3.7'
services:
  - docker

before_install:
  - docker build --build-arg TRAVIS=true -t scartography/opensartoolkit:travis .
  - docker run scartography/opensartoolkit:travis /bin/sh -c "cd OpenSarToolkit; pytest -v --cov=ost tests/;"

script:
  - pytest -v --cov=ost tests/

after_success:
  - coveralls