language: python
python:
  - '3.7'
services:
  - docker
env:
  TRAVIS=True
before_install:
  - docker pull scartography/opensartoolkit:latest
  - docker run scartography/opensartoolkit:latest /bin/sh -c "cd OpenSarToolkit; pip uninstall ost; git checkout $TRAVIS_BRANCH; git pull; python setup.py install; pytest -v --cov=ost tests/;"

script:
  - pytest -v --cov=ost tests/

after_success:
  - coveralls