dist: bionic
sudo: required
language: python
python:
  - '3.6'
services:
  - docker

before_install:
  - docker build -t scartography/opensartoolkit:travis --build-arg TRAVIS=true .
  - docker run scartography/opensartoolkit:travis /bin/sh -c "cd OpenSarToolkit; pytest -v --cov=ost tests/;"

script:
  - pytest -v --cov=ost tests/

after_success:
  - coveralls