dist: bionic
sudo: required
language: python
python:
  - '3.6'
services:
  - docker
before_install:
  - docker pull scartography/opensartoolkit:latest
  - docker run scartography/opensartoolkit:latest -c "cd /OpenSarToolkit; python setup.py test;"

script:
  - python setup.py test